//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.10 at 11:13:32 AM CET 
//


package no.fk.fint.arbeidstaker;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import no.fk.fint.felles.AbstraktPersonType;
import no.fk.fint.felles.Periode;


/**
 * <p>Java class for ArbeidstakerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArbeidstakerType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://fk.no/fint/felles/1.0}AbstraktPersonType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="stillinger" type="{http://fk.no/fint/arbeidstaker/1.0}StillingListe" minOccurs="0"/&gt;
 *         &lt;element name="ansettelsesperiode" type="{http://fk.no/fint/felles/1.0}PeriodeType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
import lombok.ToString;

@ToString
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArbeidstakerType", propOrder = {
    "stillinger",
    "ansettelsesperiode"
})
@XmlRootElement(name = "Arbeidstaker")
public class Arbeidstaker
    extends AbstraktPersonType
{

    @XmlElementWrapper(nillable = true)
    @XmlElement(name = "stilling", namespace = "http://fk.no/fint/arbeidstaker/1.0")
    protected List<Stilling> stillinger = new ArrayList<Stilling>();
    @XmlElement(nillable = true)
    protected Periode ansettelsesperiode;

    /**
     * Gets the value of the ansettelsesperiode property.
     * 
     * @return
     *     possible object is
     *     {@link Periode }
     *     
     */
    public Periode getAnsettelsesperiode() {
        return ansettelsesperiode;
    }

    /**
     * Sets the value of the ansettelsesperiode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Periode }
     *     
     */
    public void setAnsettelsesperiode(Periode value) {
        this.ansettelsesperiode = value;
    }

    public List<Stilling> getStillinger() {
        return stillinger;
    }

    public void setStillinger(List<Stilling> stillinger) {
        this.stillinger = stillinger;
    }

}
