//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.10 at 11:13:32 AM CET 
//


package no.fk.fint.arbeidstaker;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ArbeidstakerListe complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArbeidstakerListe"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="arbeidstaker" type="{http://fk.no/fint/arbeidstaker/1.0}ArbeidstakerType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
import lombok.ToString;

@ToString
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArbeidstakerListe", propOrder = {
    "arbeidstakere"
})
@XmlRootElement(name = "Arbeidstakere")
public class Arbeidstakere {

    @XmlElement(name = "arbeidstaker")
    protected List<Arbeidstaker> arbeidstakere;

    /**
     * Gets the value of the arbeidstakere property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the arbeidstakere property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArbeidstakere().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Arbeidstaker }
     * 
     * 
     */
    public List<Arbeidstaker> getArbeidstakere() {
        if (arbeidstakere == null) {
            arbeidstakere = new ArrayList<Arbeidstaker>();
        }
        return this.arbeidstakere;
    }

}
