//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.10 at 11:13:32 AM CET 
//


package no.fk.fint.arbeidstaker;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the no.fk.fint.arbeidstaker package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: no.fk.fint.arbeidstaker
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Arbeidstakere }
     * 
     */
    public Arbeidstakere createArbeidstakere() {
        return new Arbeidstakere();
    }

    /**
     * Create an instance of {@link Arbeidstaker }
     * 
     */
    public Arbeidstaker createArbeidstaker() {
        return new Arbeidstaker();
    }

    /**
     * Create an instance of {@link Stilling }
     * 
     */
    public Stilling createStilling() {
        return new Stilling();
    }

}
