//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.10 at 11:13:32 AM CET 
//


package no.fk.fint.arbeidstaker;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import no.fk.fint.felles.Periode;


/**
 * <p>Java class for StillingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StillingType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="avdeling" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="funksjon" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="grunnlonn" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="organisasjon" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="stillingskode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="stillingsnummer" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="stillingsprosent" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="stillingstittel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ansettelsestype" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="stillingsperiode" type="{http://fk.no/fint/felles/1.0}PeriodeType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
import lombok.ToString;

@ToString
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StillingType", propOrder = {
    "avdeling",
    "funksjon",
    "grunnlonn",
    "organisasjon",
    "status",
    "stillingskode",
    "stillingsnummer",
    "stillingsprosent",
    "stillingstittel",
    "ansettelsestype",
    "stillingsperiode"
})
@XmlRootElement(name = "Stilling")
public class Stilling {

    @XmlElement(nillable = true)
    protected String avdeling;
    @XmlElement(nillable = true)
    protected String funksjon;
    protected double grunnlonn;
    @XmlElement(nillable = true)
    protected String organisasjon;
    @XmlElement(required = true)
    protected String status;
    @XmlElement(nillable = true)
    protected String stillingskode;
    @XmlElement(nillable = true)
    protected BigInteger stillingsnummer;
    @XmlElement(nillable = true)
    protected Double stillingsprosent;
    @XmlElement(nillable = true)
    protected String stillingstittel;
    @XmlElement(required = true)
    protected String ansettelsestype;
    @XmlElement(nillable = true)
    protected Periode stillingsperiode;

    /**
     * Gets the value of the avdeling property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvdeling() {
        return avdeling;
    }

    /**
     * Sets the value of the avdeling property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvdeling(String value) {
        this.avdeling = value;
    }

    /**
     * Gets the value of the funksjon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFunksjon() {
        return funksjon;
    }

    /**
     * Sets the value of the funksjon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFunksjon(String value) {
        this.funksjon = value;
    }

    /**
     * Gets the value of the grunnlonn property.
     * 
     */
    public double getGrunnlonn() {
        return grunnlonn;
    }

    /**
     * Sets the value of the grunnlonn property.
     * 
     */
    public void setGrunnlonn(double value) {
        this.grunnlonn = value;
    }

    /**
     * Gets the value of the organisasjon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganisasjon() {
        return organisasjon;
    }

    /**
     * Sets the value of the organisasjon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganisasjon(String value) {
        this.organisasjon = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the stillingskode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStillingskode() {
        return stillingskode;
    }

    /**
     * Sets the value of the stillingskode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStillingskode(String value) {
        this.stillingskode = value;
    }

    /**
     * Gets the value of the stillingsnummer property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStillingsnummer() {
        return stillingsnummer;
    }

    /**
     * Sets the value of the stillingsnummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStillingsnummer(BigInteger value) {
        this.stillingsnummer = value;
    }

    /**
     * Gets the value of the stillingsprosent property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getStillingsprosent() {
        return stillingsprosent;
    }

    /**
     * Sets the value of the stillingsprosent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setStillingsprosent(Double value) {
        this.stillingsprosent = value;
    }

    /**
     * Gets the value of the stillingstittel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStillingstittel() {
        return stillingstittel;
    }

    /**
     * Sets the value of the stillingstittel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStillingstittel(String value) {
        this.stillingstittel = value;
    }

    /**
     * Gets the value of the ansettelsestype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnsettelsestype() {
        return ansettelsestype;
    }

    /**
     * Sets the value of the ansettelsestype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnsettelsestype(String value) {
        this.ansettelsestype = value;
    }

    /**
     * Gets the value of the stillingsperiode property.
     * 
     * @return
     *     possible object is
     *     {@link Periode }
     *     
     */
    public Periode getStillingsperiode() {
        return stillingsperiode;
    }

    /**
     * Sets the value of the stillingsperiode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Periode }
     *     
     */
    public void setStillingsperiode(Periode value) {
        this.stillingsperiode = value;
    }

}
