//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.10 at 11:13:32 AM CET 
//


package no.fk.fint.felles;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import no.fk.fint.arbeidstaker.Arbeidstaker;


/**
 * <p>Java class for AbstraktPersonType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstraktPersonType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://fk.no/fint/felles/1.0}AbstraktAktoerType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="fulltNavn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="navn" type="{http://fk.no/fint/felles/1.0}PersonnavnType"/&gt;
 *         &lt;element name="kjoenn" type="{http://fk.no/fint/felles/1.0}KjoennType" minOccurs="0"/&gt;
 *         &lt;element name="statsborgerskap" type="{http://fk.no/fint/felles/1.0}LandkodeType" minOccurs="0"/&gt;
 *         &lt;element name="foedselsdato" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="sivilstand" type="{http://fk.no/fint/felles/1.0}SivilstandType" minOccurs="0"/&gt;
 *         &lt;element name="adresser" type="{http://fk.no/fint/felles/1.0}AdresseListe" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
import lombok.ToString;

@ToString
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstraktPersonType", propOrder = {
    "fulltNavn",
    "navn",
    "kjoenn",
    "statsborgerskap",
    "foedselsdato",
    "sivilstand",
    "adresser"
})
@XmlSeeAlso({
    Arbeidstaker.class
})
public abstract class AbstraktPersonType
    extends AbstraktAktoerType
{

    @XmlElement(nillable = true)
    protected String fulltNavn;
    @XmlElement(required = true)
    protected Personnavn navn;
    @XmlElement(nillable = true)
    @XmlSchemaType(name = "string")
    protected KjoennType kjoenn;
    @XmlElement(nillable = true)
    protected Landkode statsborgerskap;
    @XmlElement(nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar foedselsdato;
    @XmlElement(nillable = true)
    @XmlSchemaType(name = "string")
    protected SivilstandType sivilstand;
    @XmlElementWrapper(nillable = true)
    @XmlElement(name = "adresse", namespace = "http://fk.no/fint/felles/1.0")
    protected List<Adresse> adresser = new ArrayList<Adresse>();

    /**
     * Gets the value of the fulltNavn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFulltNavn() {
        return fulltNavn;
    }

    /**
     * Sets the value of the fulltNavn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFulltNavn(String value) {
        this.fulltNavn = value;
    }

    /**
     * Gets the value of the navn property.
     * 
     * @return
     *     possible object is
     *     {@link Personnavn }
     *     
     */
    public Personnavn getNavn() {
        return navn;
    }

    /**
     * Sets the value of the navn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Personnavn }
     *     
     */
    public void setNavn(Personnavn value) {
        this.navn = value;
    }

    /**
     * Gets the value of the kjoenn property.
     * 
     * @return
     *     possible object is
     *     {@link KjoennType }
     *     
     */
    public KjoennType getKjoenn() {
        return kjoenn;
    }

    /**
     * Sets the value of the kjoenn property.
     * 
     * @param value
     *     allowed object is
     *     {@link KjoennType }
     *     
     */
    public void setKjoenn(KjoennType value) {
        this.kjoenn = value;
    }

    /**
     * Gets the value of the statsborgerskap property.
     * 
     * @return
     *     possible object is
     *     {@link Landkode }
     *     
     */
    public Landkode getStatsborgerskap() {
        return statsborgerskap;
    }

    /**
     * Sets the value of the statsborgerskap property.
     * 
     * @param value
     *     allowed object is
     *     {@link Landkode }
     *     
     */
    public void setStatsborgerskap(Landkode value) {
        this.statsborgerskap = value;
    }

    /**
     * Gets the value of the foedselsdato property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFoedselsdato() {
        return foedselsdato;
    }

    /**
     * Sets the value of the foedselsdato property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFoedselsdato(XMLGregorianCalendar value) {
        this.foedselsdato = value;
    }

    /**
     * Gets the value of the sivilstand property.
     * 
     * @return
     *     possible object is
     *     {@link SivilstandType }
     *     
     */
    public SivilstandType getSivilstand() {
        return sivilstand;
    }

    /**
     * Sets the value of the sivilstand property.
     * 
     * @param value
     *     allowed object is
     *     {@link SivilstandType }
     *     
     */
    public void setSivilstand(SivilstandType value) {
        this.sivilstand = value;
    }

    public List<Adresse> getAdresser() {
        return adresser;
    }

    public void setAdresser(List<Adresse> adresser) {
        this.adresser = adresser;
    }

}
