//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.10 at 11:13:32 AM CET 
//


package no.fk.fint.felles;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AbstraktAktoerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstraktAktoerType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="identifikatorer" type="{http://fk.no/fint/felles/1.0}IdentifikatorListe" minOccurs="0"/&gt;
 *         &lt;element name="kontaktinformasjoner" type="{http://fk.no/fint/felles/1.0}KontaktinformasjonListe" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
import lombok.ToString;

@ToString
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstraktAktoerType", propOrder = {
    "identifikatorer",
    "kontaktinformasjoner"
})
@XmlSeeAlso({
    AbstraktEnhet.class,
    AbstraktPersonType.class
})
public abstract class AbstraktAktoerType {

    @XmlElementWrapper(nillable = true)
    @XmlElement(name = "identifikator", namespace = "http://fk.no/fint/felles/1.0")
    protected List<Identifikator> identifikatorer = new ArrayList<Identifikator>();
    @XmlElementWrapper(nillable = true)
    @XmlElement(name = "kontaktinformasjon", namespace = "http://fk.no/fint/felles/1.0")
    protected List<Kontaktinformasjon> kontaktinformasjoner = new ArrayList<Kontaktinformasjon>();

    public List<Identifikator> getIdentifikatorer() {
        return identifikatorer;
    }

    public void setIdentifikatorer(List<Identifikator> identifikatorer) {
        this.identifikatorer = identifikatorer;
    }

    public List<Kontaktinformasjon> getKontaktinformasjoner() {
        return kontaktinformasjoner;
    }

    public void setKontaktinformasjoner(List<Kontaktinformasjon> kontaktinformasjoner) {
        this.kontaktinformasjoner = kontaktinformasjoner;
    }

}
