//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.10 at 11:13:32 AM CET 
//


package no.fk.fint.felles;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for IdentifikatorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IdentifikatorType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="identifikatorverdi" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="identifikatortype" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="utstedtdato" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="utstedtAvAutoritet" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="gyldighetsperiode" type="{http://fk.no/fint/felles/1.0}PeriodeType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
import lombok.ToString;

@ToString
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IdentifikatorType", propOrder = {
    "identifikatorverdi",
    "identifikatortype",
    "utstedtdato",
    "utstedtAvAutoritet",
    "gyldighetsperiode"
})
@XmlRootElement(name = "Identifikator")
public class Identifikator {

    @XmlElement(required = true)
    protected String identifikatorverdi;
    @XmlElement(required = true)
    protected String identifikatortype;
    @XmlElement(nillable = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar utstedtdato;
    @XmlElement(nillable = true)
    protected String utstedtAvAutoritet;
    @XmlElement(nillable = true)
    protected Periode gyldighetsperiode;

    /**
     * Gets the value of the identifikatorverdi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifikatorverdi() {
        return identifikatorverdi;
    }

    /**
     * Sets the value of the identifikatorverdi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentifikatorverdi(String value) {
        this.identifikatorverdi = value;
    }

    /**
     * Gets the value of the identifikatortype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifikatortype() {
        return identifikatortype;
    }

    /**
     * Sets the value of the identifikatortype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentifikatortype(String value) {
        this.identifikatortype = value;
    }

    /**
     * Gets the value of the utstedtdato property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUtstedtdato() {
        return utstedtdato;
    }

    /**
     * Sets the value of the utstedtdato property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUtstedtdato(XMLGregorianCalendar value) {
        this.utstedtdato = value;
    }

    /**
     * Gets the value of the utstedtAvAutoritet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUtstedtAvAutoritet() {
        return utstedtAvAutoritet;
    }

    /**
     * Sets the value of the utstedtAvAutoritet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUtstedtAvAutoritet(String value) {
        this.utstedtAvAutoritet = value;
    }

    /**
     * Gets the value of the gyldighetsperiode property.
     * 
     * @return
     *     possible object is
     *     {@link Periode }
     *     
     */
    public Periode getGyldighetsperiode() {
        return gyldighetsperiode;
    }

    /**
     * Sets the value of the gyldighetsperiode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Periode }
     *     
     */
    public void setGyldighetsperiode(Periode value) {
        this.gyldighetsperiode = value;
    }

}
