//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.10 at 11:13:32 AM CET 
//


package no.fk.fint.felles;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for KjoennType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="KjoennType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="kvinne"/&gt;
 *     &lt;enumeration value="mann"/&gt;
 *     &lt;enumeration value="ubestemt"/&gt;
 *     &lt;enumeration value="ukjent"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "KjoennType")
@XmlEnum
public enum KjoennType {

    @XmlEnumValue("kvinne")
    KVINNE("kvinne"),
    @XmlEnumValue("mann")
    MANN("mann"),
    @XmlEnumValue("ubestemt")
    UBESTEMT("ubestemt"),
    @XmlEnumValue("ukjent")
    UKJENT("ukjent");
    private final String value;

    KjoennType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static KjoennType fromValue(String v) {
        for (KjoennType c: KjoennType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
